# Generated by Django 3.2.3 on 2021-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuemiao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subinfomodel',
            name='retryTime',
        ),
        migrations.AddField(
            model_name='subinfomodel',
            name='retryStartTime',
            field=models.DateTimeField(null=True, verbose_name='重试开始时间'),
        ),
    ]
